export const cities = [
  "Helsinki",
  "Espoo",
  "Vantaa",
  "Tampere",
  "Turku",
  "Jyväskylä",
  "Lahti",
  "Oulu",
  "Kuopio",
  "Pori",
  "Vaasa",
  "Seinäjoki",
  "Hämeenlinna",
  "Lappeenranta",
  "Joensuu",
  "Kouvola",
  "Mikkeli",
  "Rovaniemi",
  "Hyvinkää",
  "Riihimäki",
  "Jämsä",
  "Orivesi",
  "Nokia",
  "Kangasala",
  "Ylöjärvi",
  "Pirkkala",
] as const;

export const serviceCategories = [
  "Parturi",
  "Kampaaja",
  "Kynnet",
  "Ripset",
  "Kulmat",
  "Meikkaus",
  "Ihonhoito",
  "Barber",
  "Fade-leikkaukset",
  "Hiusten värjäys",
  "Kampaukset",
  "Häämeikki",
  "Opiskelijatekijä",
  "Kotitekijä",
] as const;

export const contactEmail = "stylistbeta@gmail.com";
